In [51]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic-train-csv/titanic_train.csv


### NUMPY

In [52]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr)


[1 2 3 4]


In [53]:
arr1=np.array([[1,4,5,56,7],[6,8,9,346,0]])
arr1

array([[  1,   4,   5,  56,   7],
       [  6,   8,   9, 346,   0]])

In [54]:
import numpy as np

arr = np.array(42)

print(arr)


42


In [55]:

arr1 = np.array(76)
print(arr1)

76


In [56]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)


[1 2 3 4 5]


In [57]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [58]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)


[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [59]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)


0
1
2
3


In [60]:
import numpy as np

arr = np.array([1, 2, 3, 4,5], ndmin=6)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[[1 2 3 4 5]]]]]]
number of dimensions : 6


In [61]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


In [62]:
arr1=np.array([[1,4,5,56,7],[6,8,9,346,0]])
print(arr.ndim)
print(arr.shape)

2
(2, 4)


In [63]:
arr1[[0,1],2]

array([5, 9])

In [64]:
arr1[:,1::2]

array([[  4,  56],
       [  8, 346]])

In [65]:
arr1[:,3]

array([ 56, 346])

In [66]:
arr1[1,1]=200
arr1

array([[  1,   4,   5,  56,   7],
       [  6, 200,   9, 346,   0]])

In [67]:
arr1[:,1:3]=[[45,66],[23,34]]
arr1

array([[  1,  45,  66,  56,   7],
       [  6,  23,  34, 346,   0]])

In [68]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [69]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [70]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [71]:
arr1=np.arange(2, 10, 2)  
arr1


array([2, 4, 6, 8])

In [72]:
arr1 = arr1.reshape(2,2)
arr1


array([[2, 4],
       [6, 8]])

In [73]:
arr = np.array([10, 20, 30, 40])
print(arr[1])


20


In [74]:
print(arr[3])

40


In [75]:
matrix = np.array([[1, 2], [3, 4]])
print(matrix[1][0])


3


In [76]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])


[20 30 40]


In [77]:
arr = np.array([1, 2, 3])
print(arr.dtype)


int64


In [78]:
a=np.arange(1,6)
a=np.arange(1,6)
z=[15,3,5]
np.concatenate([a,b,z])

array([ 1,  2,  3,  4,  5,  1,  2,  3,  4,  5, 15,  3,  5])

In [79]:
a = np.array([1, 2])
b = np.array([3, 4])
c = np.concatenate((a, b))
print(c)


[1 2 3 4]


In [80]:
np.linspace(2,5,13)

array([2.  , 2.25, 2.5 , 2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 ,
       4.75, 5.  ])

In [81]:
arr1

array([[2, 4],
       [6, 8]])

In [82]:
arr1.ravel()

array([2, 4, 6, 8])

In [83]:

arr = np.array([1, 2, 3, 4])
x = np.where(arr == 3)
print(x)


(array([2]),)


In [84]:
print(np.random.rand())           
print(np.random.rand(6))          
print(np.random.rand(2, 6))


0.9520188459774898
[0.39722985 0.4762218  0.78611498 0.47178794 0.38295551 0.55634604]
[[0.02039458 0.33898271 0.71771979 0.54380044 0.10839007 0.93130385]
 [0.88424887 0.16403907 0.42421895 0.4868076  0.67730697 0.98960473]]


### PANDAS

In [85]:
import pandas as pd

In [86]:
import pandas as pd

df = pd.DataFrame(
    data=[
        [1, 2, 3, 4, 5],
        [1, 2, 3, 4, 5]
    ],
    columns=['eng', 'math', 'pun', 'sci', 'cs'],
    index=['a', 'b'],
    dtype='float'
)

df


eng  math  pun  sci   cs
a  1.0   2.0  3.0  4.0  5.0
b  1.0   2.0  3.0  4.0  5.0

In [87]:
data=pd.DataFrame({'country':['India','Nepal','Pakistan','Bhutan'],'Rank':[11,34,40,130]})
data

country  Rank
0     India    11
1     Nepal    34
2  Pakistan    40
3    Bhutan   130

In [88]:
import pandas as pd

students = pd.DataFrame({
    'Name': ['Aman', 'Simran', 'Ravi', 'Jaspreet'],
    'Age': [18, 19, 17, 18],
    'Marks': [88, 92, 75, 85]
})

print(students)


       Name  Age  Marks
0      Aman   18     88
1    Simran   19     92
2      Ravi   17     75
3  Jaspreet   18     85


In [89]:
data.describe()

Rank
count    4.000000
mean    53.750000
std     52.347397
min     11.000000
25%     28.250000
50%     37.000000
75%     62.500000
max    130.000000

In [90]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   country  4 non-null      object
 1   Rank     4 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 196.0+ bytes


In [91]:
data.sort_values(by=['Rank'])

country  Rank
0     India    11
1     Nepal    34
2  Pakistan    40
3    Bhutan   130

In [92]:
data.isnull().sum()

country    0
Rank       0
dtype: int64

In [93]:
data[data.duplicated()]

Empty DataFrame
Columns: [country, Rank]
Index: []

In [94]:
data.loc[1]

country    Nepal
Rank          34
Name: 1, dtype: object

In [95]:
data.iloc()

In [96]:
data.dropna()
data

country  Rank
0     India    11
1     Nepal    34
2  Pakistan    40
3    Bhutan   130

In [97]:
data.value_counts()

country   Rank
Bhutan    130     1
India     11      1
Nepal     34      1
Pakistan  40      1
Name: count, dtype: int64

In [98]:
data.groupby('country')['Rank'].sum()

country
Bhutan      130
India        11
Nepal        34
Pakistan     40
Name: Rank, dtype: int64

In [9]:
import os
import pandas as pd

for dirname, subdirs, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


df = pd.read_csv('/kaggle/input/titanic-train-csv/titanic_train.csv')
df.head()


/kaggle/input/titanic-train-csv/titanic_train.csv


PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [11]:
df.shape

(891, 12)

In [101]:
df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [14]:
df[df.duplicated()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

In [15]:
df['Age']>32

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)


0      False
1       True
2      False
3       True
4       True
       ...  
886    False
887    False
888    False
889    False
890    False
Name: Age, Length: 891, dtype: bool

In [19]:
df[df['Age']>32].head()

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)


PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
4             5         0       3   
6             7         0       1   
11           12         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                            Allen, Mr. William Henry    male  35.0      0   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   

    Parch    Ticket     Fare Cabin Embarked  
1       0  PC 17599  71.2833   C85        C  
3       0    113803  53.1000  C123        S  
4       0    373450   8.0500   NaN        S  
6       0     17463  51.8625   E46        S  
11      0    113783  26.5500  C103        S

In [21]:
df[df['Age']>32].tail(10)

/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)


PassengerId  Survived  Pclass  \
857          858         1       1   
860          861         0       3   
862          863         1       1   
865          866         1       2   
871          872         1       1   
872          873         0       1   
873          874         0       3   
879          880         1       1   
881          882         0       3   
885          886         0       3   

                                                  Name     Sex   Age  SibSp  \
857                             Daly, Mr. Peter Denis     male  51.0      0   
860                            Hansen, Mr. Claus Peter    male  41.0      2   
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  female  48.0      0   
865                           Bystrom, Mrs. (Karolina)  female  42.0      0   
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
872                           Carlsson, Mr. Frans Olof    male  33.0      0   
873                        Vander Cruyssen, Mr. Victor    male  47.0      0   
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
881                                 Markun, Mr. Johann    male  33.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   

     Parch  Ticket     Fare        Cabin Embarked  
857      0  113055  26.5500          E17        S  
860      0  350026  14.1083          NaN        S  
862      0   17466  25.9292          D17        S  
865      0  236852  13.0000          NaN        S  
871      1   11751  52.5542          D35        S  
872      0     695   5.0000  B51 B53 B55        S  
873      0  345765   9.0000          NaN        S  
879      1   11767  83.1583          C50        C  
881      0  349257   7.8958          NaN        S  
885      5  382652  29.1250          NaN        Q

In [23]:
df[df['Sex']=='male']

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


PassengerId  Survived  Pclass                            Name   Sex  \
0              1         0       3         Braund, Mr. Owen Harris  male   
4              5         0       3        Allen, Mr. William Henry  male   
5              6         0       3                Moran, Mr. James  male   
6              7         0       1         McCarthy, Mr. Timothy J  male   
7              8         0       3  Palsson, Master. Gosta Leonard  male   
..           ...       ...     ...                             ...   ...   
883          884         0       2   Banfield, Mr. Frederick James  male   
884          885         0       3          Sutehall, Mr. Henry Jr  male   
886          887         0       2           Montvila, Rev. Juozas  male   
889          890         1       1           Behr, Mr. Karl Howell  male   
890          891         0       3             Dooley, Mr. Patrick  male   

      Age  SibSp  Parch            Ticket     Fare Cabin Embarked  
0    22.0      1      0         A/5 21171   7.2500   NaN        S  
4    35.0      0      0            373450   8.0500   NaN        S  
5     NaN      0      0            330877   8.4583   NaN        Q  
6    54.0      0      0             17463  51.8625   E46        S  
7     2.0      3      1            349909  21.0750   NaN        S  
..    ...    ...    ...               ...      ...   ...      ...  
883  28.0      0      0  C.A./SOTON 34068  10.5000   NaN        S  
884  25.0      0      0   SOTON/OQ 392076   7.0500   NaN        S  
886  27.0      0      0            211536  13.0000   NaN        S  
889  26.0      0      0            111369  30.0000  C148        C  
890  32.0      0      0            370376   7.7500   NaN        Q  

[577 rows x 12 columns]

In [24]:
df[df['Sex']=='female']

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


PassengerId  Survived  Pclass  \
1              2         1       1   
2              3         1       3   
3              4         1       1   
8              9         1       3   
9             10         1       2   
..           ...       ...     ...   
880          881         1       2   
882          883         0       3   
885          886         0       3   
887          888         1       1   
888          889         0       3   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
..                                                 ...     ...   ...    ...   
880       Shelley, Mrs. William (Imanita Parrish Hall)  female  25.0      0   
882                       Dahlberg, Miss. Gerda Ulrika  female  22.0      0   
885               Rice, Mrs. William (Margaret Norton)  female  39.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   

     Parch            Ticket     Fare Cabin Embarked  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
8        2            347742  11.1333   NaN        S  
9        0            237736  30.0708   NaN        C  
..     ...               ...      ...   ...      ...  
880      1            230433  26.0000   NaN        S  
882      0              7552  10.5167   NaN        S  
885      5            382652  29.1250   NaN        Q  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  

[314 rows x 12 columns]

In [26]:
person=df[['Name','Age','Fare']]
person

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


Name   Age     Fare
0                              Braund, Mr. Owen Harris  22.0   7.2500
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0  71.2833
2                               Heikkinen, Miss. Laina  26.0   7.9250
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0  53.1000
4                             Allen, Mr. William Henry  35.0   8.0500
..                                                 ...   ...      ...
886                              Montvila, Rev. Juozas  27.0  13.0000
887                       Graham, Miss. Margaret Edith  19.0  30.0000
888           Johnston, Miss. Catherine Helen "Carrie"   NaN  23.4500
889                              Behr, Mr. Karl Howell  26.0  30.0000
890                                Dooley, Mr. Patrick  32.0   7.7500

[891 rows x 3 columns]

In [28]:
df[(df['Age'] > 25) & (df['Age'] < 32)]


/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in greater
  return op(a, b)
/usr/local/lib/python3.11/dist-packages/pandas/core/computation/expressions.py:73: RuntimeWarning: invalid value encountered in less
  return op(a, b)


PassengerId  Survived  Pclass  \
2              3         1       3   
8              9         1       3   
18            19         0       3   
23            24         1       1   
34            35         0       1   
..           ...       ...     ...   
870          871         0       3   
874          875         1       2   
883          884         0       2   
886          887         0       2   
889          890         1       1   

                                                  Name     Sex   Age  SibSp  \
2                               Heikkinen, Miss. Laina  female  26.0      0   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
23                        Sloper, Mr. William Thompson    male  28.0      0   
34                             Meyer, Mr. Edgar Joseph    male  28.0      1   
..                                                 ...     ...   ...    ...   
870                                  Balkic, Mr. Cerin    male  26.0      0   
874              Abelson, Mrs. Samuel (Hannah Wizosky)  female  28.0      1   
883                      Banfield, Mr. Frederick James    male  28.0      0   
886                              Montvila, Rev. Juozas    male  27.0      0   
889                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch            Ticket     Fare Cabin Embarked  
2        0  STON/O2. 3101282   7.9250   NaN        S  
8        2            347742  11.1333   NaN        S  
18       0            345763  18.0000   NaN        S  
23       0            113788  35.5000    A6        S  
34       0          PC 17604  82.1708   NaN        C  
..     ...               ...      ...   ...      ...  
870      0            349248   7.8958   NaN        S  
874      0         P/PP 3381  24.0000   NaN        C  
883      0  C.A./SOTON 34068  10.5000   NaN        S  
886      0            211536  13.0000   NaN        S  
889      0            111369  30.0000  C148        C  

[127 rows x 12 columns]

In [30]:
type(df['Age'])

pandas.core.series.Series

In [169]:
type(df['Sex'])

pandas.core.series.Series

In [32]:
df['Age']

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [34]:
df['Fare']

0       7.2500
1      71.2833
2       7.9250
3      53.1000
4       8.0500
        ...   
886    13.0000
887    30.0000
888    23.4500
889    30.0000
890     7.7500
Name: Fare, Length: 891, dtype: float64

In [36]:
df[['Sex','Age']].groupby('Sex')

In [38]:
df[(df['Age'] > 32) & (df['Age'] < 35)][['Name', 'Age', 'SibSp', 'Parch']]


Name   Age  SibSp  Parch
21                               Beesley, Mr. Lawrence  34.0      0      0
85   Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...  33.0      3      0
98                Doling, Mrs. John T (Ada Julia Bone)  34.0      0      1
99                                   Kantor, Mr. Sinai  34.0      1      0
103                         Johansson, Mr. Gustaf Joel  33.0      0      0
122                               Nasser, Mr. Nicholas  32.5      1      0
123                                Webber, Miss. Susan  32.5      0      0
130                               Drazenoic, Mr. Jozef  33.0      0      0
202                         Johanson, Mr. Jakob Alfred  34.0      0      0
239                             Hunt, Mr. George Henry  33.0      0      0
285                                Stankovic, Mr. Ivan  33.0      0      0
405                                 Gale, Mr. Shadrach  34.0      1      0
412                             Minahan, Miss. Daisy E  33.0      1      0
416    Drew, Mrs. James Vivian (Lulu Thorne Christian)  34.0      1      1
447                        Seward, Mr. Frederic Kimber  34.0      0      0
461                                Morley, Mr. William  34.0      0      0
472            West, Mrs. Edwy Arthur (Ada Mary Worth)  33.0      1      2
476                            Renouf, Mr. Peter Henry  34.0      1      0
506      Quick, Mrs. Frederick Charles (Jane Richards)  33.0      0      2
516                       Lemore, Mrs. (Amelia Milley)  34.0      0      0
548                          Goldsmith, Mr. Frank John  33.0      1      1
576                               Garside, Miss. Ethel  34.0      0      0
616                          Danbom, Mr. Ernst Gilbert  34.0      1      1
719                       Johnson, Mr. Malkolm Joackim  33.0      0      0
722                       Gillespie, Mr. William Henry  34.0      0      0
752                   Vande Velde, Mr. Johannes Joseph  33.0      0      0
758                       Theobald, Mr. Thomas Leonard  34.0      0      0
759  Rothes, the Countess. of (Lucy Noel Martha Dye...  33.0      0      0
800                               Ponesell, Mr. Martin  34.0      0      0
809     Chambers, Mrs. Norman Campbell (Bertha Griggs)  33.0      1      0
843                         Lemberopolous, Mr. Peter L  34.5      0      0
872                           Carlsson, Mr. Frans Olof  33.0      0      0
881                                 Markun, Mr. Johann  33.0      0      0