In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [52]:
import numpy as np
import pandas as pd
df=pd.read_csv('/kaggle/input/customer1-csv/customer (1).csv')

from sklearn.preprocessing import OrdinalEncoder
import pandas as pd
data=pd.DataFrame({'Color':['Red','Green','Blue','Green','Red']})
encoder=OrdinalEncoder()
encoded=encoder.fit_transform(data)
print(encoded)
df.sample(5)


[[2.]
 [1.]
 [0.]
 [1.]
 [2.]]


age  gender   review education purchased
49   25  Female     Good        UG        No
34   86    Male  Average    School        No
11   74    Male     Good        UG       Yes
45   61    Male     Poor        PG       Yes
2    70  Female     Good        PG        No

In [53]:
df=df.iloc[:,2:]
df.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

#### Ordinal Encoder

In [54]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(df.drop(columns=['purchased']),df['purchased'],test_size=0.20,random_state=2)
X_train

review education
24  Average        PG
48     Good        UG
17     Poor        UG
12     Poor    School
27     Poor        PG
33     Good        PG
16     Poor        UG
2      Good        PG
25     Good    School
14     Poor        PG
30  Average        UG
5   Average    School
32  Average        UG
1      Poor        UG
29  Average        UG
35     Poor    School
41     Good        PG
19     Poor        PG
37  Average        PG
10     Good        UG
4   Average        UG
6      Good    School
3      Good        PG
20  Average    School
26     Poor        PG
38     Good    School
21  Average        PG
42     Good        PG
31     Poor    School
34  Average    School
7      Poor    School
49     Good        UG
11     Good        UG
18     Good    School
43     Poor        PG
22     Poor        PG
8   Average        UG
45     Poor        PG
15     Poor        UG
40     Good    School

In [55]:
Y_train

24    Yes
48    Yes
17    Yes
12     No
27     No
33    Yes
16    Yes
2      No
25     No
14    Yes
30     No
5     Yes
32    Yes
1      No
29    Yes
35    Yes
41    Yes
19    Yes
37    Yes
10    Yes
4      No
6      No
3      No
20    Yes
26     No
38     No
21     No
42    Yes
31    Yes
34     No
7     Yes
49     No
11    Yes
18     No
43     No
22    Yes
8      No
45    Yes
15     No
40     No
Name: purchased, dtype: object

In [56]:
oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [57]:
X_train=oe.transform(X_train)
X_train

array([[1., 2.],
       [2., 1.],
       [0., 1.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [2., 2.],
       [2., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [0., 2.],
       [1., 2.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 2.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 1.],
       [2., 0.]])

#### Label Encoder

In [58]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit(Y_train)

LabelEncoder()

In [59]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [60]:
Y_train=le.transform(Y_train)
Y_test=le.transform(Y_test)
Y_train

array([1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0])

In [62]:
import pandas as pd
df = pd.DataFrame({
    'color': ['red', 'blue', 'green'],
    'size': ['S', 'M', 'L']
})

numerics = pd.get_dummies(df, columns=['color', 'size'])

print(numerics)


   color_blue  color_green  color_red  size_L  size_M  size_S
0       False        False       True   False   False    True
1        True        False      False   False    True   False
2       False         True      False    True   False   False


#### OneHot Encoder

In [63]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

df = pd.DataFrame({
    'color': ['red', 'blue', 'green'],
    'size': ['S', 'M', 'L']
})
features = df[['color', 'size']]
encoder = OneHotEncoder(drop='first', sparse_output=False)
encoded = encoder.fit_transform(features).astype(int)
feature_names = encoder.get_feature_names_out(['color', 'size'])

encoded_df = pd.DataFrame(encoded, columns=feature_names)
print(encoded_df)



   color_green  color_red  size_M  size_S
0            0          1       0       1
1            0          0       1       0
2            1          0       0       0


In [65]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
df = pd.DataFrame({
    'color': ['red', 'blue', 'green'],
    'size': ['S', 'M', 'L']
})
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
encoded = encoder.fit_transform(df)
column_names = encoder.get_feature_names_out(['color', 'size'])
encoded_df = pd.DataFrame(encoded, columns=column_names)
print(encoded_df)


   color_blue  color_green  color_red  size_L  size_M  size_S
0         0.0          0.0        1.0     0.0     0.0     1.0
1         1.0          0.0        0.0     0.0     1.0     0.0
2         0.0          1.0        0.0     1.0     0.0     0.0
